### PR TITLE
add TLS setting in readme

### PR DESCRIPTION
**Pull request by daixiang0**
There is not details about fill out which val into TLS setting field.

According to "How to configure cluster #35", add related info.

Signed-off-by: Xiang Dai <xiang.dai@iluvatar.ai>

### CODE REVIEW

**Comment by daixiang0** [comment]
any input?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
@jtlisi @daniellee any update?

**Comment by daixiang0** [comment]
any update?

**Comment by shashikant-koder** [comment]
any update on this please?

**Comment by daixiang0** [comment]
@jtlisi Hi, any update please?

**Comment by daixiang0** [comment]
@jtlisi Hi, any update please?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by dennisameling** [comment]
@daixiang0 sorry, but I'm not a maintainer of this project, so can't help you further.

**Comment by daixiang0** [comment]
@dennisameling do you know who is?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
@daniellee hi, any input?

**Comment by daixiang0** [comment]
@jtlisi thanks!

**Pull request merged**
